"""SAVEDEAL 운영 Agent가 쓰는 상태·문제·해결책 코드와 화면 표시용 한글 이름."""

# 예약 진행상태
STATUS_ACTION_REQUIRED = "ACTION_REQUIRED"
STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_READY = "READY"
STATUS_COMPLETED = "COMPLETED"
STATUS_CANCELLED = "CANCELLED"

CLOSED_STATUSES = {STATUS_COMPLETED, STATUS_CANCELLED}

STATUS_LABELS = {
    STATUS_ACTION_REQUIRED: "처리 필요",
    STATUS_IN_PROGRESS: "해결 진행 중",
    STATUS_READY: "개통 대기",
    STATUS_COMPLETED: "개통 완료",
    STATUS_CANCELLED: "예약 취소",
}

# 문제 원인
ISSUE_STOCK_SHORTAGE = "STOCK_SHORTAGE"
ISSUE_INSTALLMENT_LIMIT = "INSTALLMENT_LIMIT"
ISSUE_MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
ISSUE_IDENTITY_FAILED = "IDENTITY_FAILED"
ISSUE_ACTIVATION_REJECTED = "ACTIVATION_REJECTED"
ISSUE_CUSTOMER_NO_RESPONSE = "CUSTOMER_NO_RESPONSE"
ISSUE_OVERDUE_PAYMENT = "OVERDUE_PAYMENT"

ISSUE_LABELS = {
    ISSUE_STOCK_SHORTAGE: "재고 미확보",
    ISSUE_INSTALLMENT_LIMIT: "할부한도 부족",
    ISSUE_MISSING_DOCUMENTS: "서류 미제출",
    ISSUE_IDENTITY_FAILED: "본인인증 실패",
    ISSUE_ACTIVATION_REJECTED: "개통 반려",
    ISSUE_CUSTOMER_NO_RESPONSE: "고객 미응답",
    ISSUE_OVERDUE_PAYMENT: "요금 미납",
}

# 해결책
ACTION_NEARBY_STORE_TRANSFER = "NEARBY_STORE_TRANSFER"
ACTION_COLOR_STORAGE_CHANGE = "COLOR_STORAGE_CHANGE"
ACTION_ALTERNATIVE_DEVICE = "ALTERNATIVE_DEVICE"
ACTION_DATE_CHANGE = "DATE_CHANGE"
ACTION_DOWN_PAYMENT = "DOWN_PAYMENT"
ACTION_INSTALLMENT_ADJUSTMENT = "INSTALLMENT_ADJUSTMENT"
ACTION_DOCUMENT_REQUEST = "DOCUMENT_REQUEST"
ACTION_IDENTITY_RETRY = "IDENTITY_RETRY"
ACTION_ACTIVATION_INPUT_FIX = "ACTIVATION_INPUT_FIX"
ACTION_CUSTOMER_RECONTACT = "CUSTOMER_RECONTACT"
ACTION_PAYMENT_GUIDE = "PAYMENT_GUIDE"
ACTION_MANAGER_ESCALATION = "MANAGER_ESCALATION"

ACTION_LABELS = {
    ACTION_NEARBY_STORE_TRANSFER: "인근 점포 재고 이동",
    ACTION_COLOR_STORAGE_CHANGE: "다른 색상·용량 제안",
    ACTION_ALTERNATIVE_DEVICE: "대체 단말 제안",
    ACTION_DATE_CHANGE: "수령일 변경",
    ACTION_DOWN_PAYMENT: "선납금 적용",
    ACTION_INSTALLMENT_ADJUSTMENT: "할부기간 조정",
    ACTION_DOCUMENT_REQUEST: "누락서류 요청",
    ACTION_IDENTITY_RETRY: "본인인증 재시도",
    ACTION_ACTIVATION_INPUT_FIX: "개통 반려 입력값 수정",
    ACTION_CUSTOMER_RECONTACT: "고객 재연락",
    ACTION_PAYMENT_GUIDE: "미납요금 납부 안내",
    ACTION_MANAGER_ESCALATION: "점장 에스컬레이션",
}

# 해결책 상태
ACTION_PROPOSED = "PROPOSED"
ACTION_APPROVED = "APPROVED"
ACTION_SUCCEEDED = "SUCCEEDED"
ACTION_FAILED = "FAILED"
ACTION_DISCARDED = "DISCARDED"

ACTION_STATUS_LABELS = {
    ACTION_PROPOSED: "제안",
    ACTION_APPROVED: "승인·실행 중",
    ACTION_SUCCEEDED: "성공",
    ACTION_FAILED: "실패",
    ACTION_DISCARDED: "보류",
}

# 처리이력 이벤트
EVENT_RESERVATION_CREATED = "RESERVATION_CREATED"
EVENT_ISSUE_DETECTED = "ISSUE_DETECTED"
EVENT_ACTIONS_PROPOSED = "ACTIONS_PROPOSED"
EVENT_ACTION_APPROVED = "ACTION_APPROVED"
EVENT_ACTION_SUCCEEDED = "ACTION_SUCCEEDED"
EVENT_ACTION_FAILED = "ACTION_FAILED"
EVENT_STATUS_CHANGED = "STATUS_CHANGED"
EVENT_ACTIVATION_COMPLETED = "ACTIVATION_COMPLETED"
EVENT_RESERVATION_CANCELLED = "RESERVATION_CANCELLED"

EVENT_LABELS = {
    EVENT_RESERVATION_CREATED: "예약 등록",
    EVENT_ISSUE_DETECTED: "문제 감지",
    EVENT_ACTIONS_PROPOSED: "해결책 생성",
    EVENT_ACTION_APPROVED: "해결책 승인",
    EVENT_ACTION_SUCCEEDED: "해결 완료",
    EVENT_ACTION_FAILED: "해결 실패",
    EVENT_STATUS_CHANGED: "상태 변경",
    EVENT_ACTIVATION_COMPLETED: "개통 완료",
    EVENT_RESERVATION_CANCELLED: "예약 취소",
}

LINE_TYPE_LABELS = {"NEW": "신규가입", "MNP": "번호이동", "CHANGE": "기기변경"}

RISK_LABELS = {"high": "고위험", "medium": "주의", "low": "안정"}
